HotelShevaroys/HotelShevaroys/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from webapp import views as v
from webapp import sadmin as sa
urlpatterns = [
    path('admin/', admin.site.urls),

    path('', v.index, name='index'),
    path('room/', v.room,name='room'),
    path('hall/', v.hall,name='hall'),
    path('service/', v.service,name='service'),
    path('about/', v.about,name='about'),
    path('privacy/', v.privacy,name='privacy'),
    path('gallery/', v.gallery,name='gallery'),
    path('contact/', v.contact,name='contact'),


    # rooms
    path('room/<str:roomname>',v.room_detail,name='room_detail'),
    path('booking/<str:roomname>/<str:price>/',v.bookroom,name='bookroom'),
    path('booking/payment/<str:no>/<str:n>/<str:rn>/<str:am>/<str:p>/<str:e>/',v.payment,name='payment'),
    path('booking_status/<str:o>/<str:n>/',v.success,name='success'),
    path('feedback_form/',v.feedback,name='feedback'),
    path('room_view/<str:roomname>/',v.room_view,name='room_view'),
    
    #user
    path('register', v.register, name='register'),
    path('login', v.Login, name='login'),
    path('logout', v.Logout, name='logout'),
    # path('My_Profile/',v.my_profile,name='my_profile'),
    path('My_Booking/',v.mybooking,name='mybooking'),
    path('Previous_Booking/',v.previous_booking,name='previous_booking'),
    path('Cancel_Booking_list/',v.cancel_booking_list,name='cancel_booking_list'),
    path('cancel_booking_view/<str:id>',v.cancel_booking_view,name='cancel_booking_view'),
    path('cancel_booking/<str:id>/',v.cancel_booking,name='cancel_booking'),
    
    # admin
    path('admin_dashboard/', sa.superadmin, name='superadmin'),
    path('rooms/', sa.srooms, name='srooms'),
    path('add_room/', sa.addroom, name='addroom'),
    path('edit_room/<str:id>/', sa.editroom, name='editroom'),
    path('new_booking/', sa.booking, name='booking'),
    path('conform_booking_list/', sa.bookinglist, name='bookinglist'),
    path('checkin_view/<str:id>/', sa.checkin_view, name='checkin_view'),
    path('checkin_conform/<str:id>/',sa.checkin_conform,name='checkin_conform'),
    path('checkout_view/<str:id>/', sa.checkout_view, name='checkout_view'),
    path('checkout_conform/<str:id>/',sa.checkout_conform,name='checkout_conform'),
    path('previous_conform_booking_list/', sa.prevbooking, name='prevbooking'),
    path('unconform_booking_list/', sa.unbookinglist, name='unbookinglist'),
    path('cancelled_booking_list/', sa.cancellist, name='cancellist'),
    path('update_room_image/', sa.updateimg, name='updateimg'),
    path('invoice/', sa.sinvoice, name='sinvoice'),
    path('search/conform_booking_list/',sa.search_bookinglist,name='search_bookinglist'),
    path('search/unconform_booking_list/',sa.search_unbookinglist,name='search_unbookinglist'),
    path('search/previous_conform_booking_list/',sa.search_prevbooking,name='search_prevbooking'),
    path('search/cancelled_booking_list/',sa.search_cancellist,name='search_cancellist'),
    path('customer_feedback/',sa.customer_feedback,name='customer_feedback'),

    # Reception admin
    path('reception_admin_dashboard/', sa.superadmin1, name='superadmin1'),
    path('reception_rooms/', sa.srooms1, name='srooms1'),
    path('reception_new_booking/', sa.booking1, name='booking1'),
    path('reception_conform_booking_list/', sa.bookinglist1, name='bookinglist1'),
    path('reception_checkin_view/<str:id>/', sa.checkin_view1, name='checkin_view1'),
    path('reception_checkin_conform/<str:id>/',sa.checkin_conform1,name='checkin_conform1'),
    path('reception_checkout_view/<str:id>/', sa.checkout_view1, name='checkout_view1'),
    path('reception_checkout_conform/<str:id>/',sa.checkout_conform1,name='checkout_conform1'),
    path('reception_cancelled_booking_list/', sa.cancellist1, name='cancellist1'),
    path('reception_previous_conform_booking_list/', sa.prevbooking1, name='prevbooking1'),
    path('reception_unconform_booking_list/', sa.unbookinglist1, name='unbookinglist1'),
    path('search/reception_conform_booking_list/',sa.search_bookinglist1,name='search_bookinglist1'),
    path('search/reception_unconform_booking_list/',sa.search_unbookinglist1,name='search_unbookinglist1'),
    path('search/reception_previous_conform_booking_list/',sa.search_prevbooking1,name='search_prevbooking1'),
    path('search/reception_cancelled_booking_list/',sa.search_cancellist1,name='search_cancellist1'),

    # Payment Gateway
    # path('store/',StoreDetails.as_view(),name='checkout'),
    # path('charge/',MyPayment.as_view(),),

    path('stdroom/',v.stdroom,name='stdroom'),
    path('bouvilla/',v.bouvilla,name='bouvilla'),
    path('deluxeroom/',v.deluxeroom,name='deluxeroom'),
    path('dhaliaroom/',v.dhaliaroom,name='dhaliaroom'),
    path('luxuryroom/',v.luxuryroom,name='luxuryroom'),
    path('roseroom/',v.roseroom,name='roseroom'),
    path('orchidroom/',v.orchidroom,name='orchidroom'),

    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# urlpatterns += staticfiles_urlpatterns()

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

HotelShevaroys/webapp/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid
from django.urls import reverse_lazy
from datetime import date

ROOM_STATUS = ( 
    ("Available", "Available"), 
    ("Not Available", "Not Available"),    
    ) 

ROOM_CHOICES = (
   
   ('Standard Room','Standard Room'),
   ('Bougainvilla Room','Bougainvilla Room'),
   ('Rose Room','Rose Room'),
   ('Dahlia Room','Dahlia Room'),
   ('Orchid Room','Orchid Room'),
   ('King Orchid','King Orchid'),
   ('Deluxe Villa','Deluxe Villa'),
   ('Luxury Villa','Luxury Villa'),
   
   
	)
ROOM_TYPE = (

   ('Room','Room'),
   ('Villa','Villa'),
   
  	
  	)
PAYMENT = (

   ('Cash','Cash'),
   ('Online','Online'),
       
    )
# Create your models here.
class Profile(models.Model):
  user = models.OneToOneField(User, on_delete=models.CASCADE)
  name = models.CharField(db_column="Name", max_length=50,default='')
  mobile = models.CharField(db_column="Mobile", max_length=10, default='')
  email = models.CharField(db_column="Email", max_length=100, default='')
  pass1 = models.CharField(db_column="Password", max_length=100, default='')
  admin_status = models.BooleanField(default=False)
  radmin_status = models.BooleanField(default=False)

  def __str__(self):
    return f'{self.name}'



class Room(models.Model):
    
    #type,no_of_rooms,capacity,prices,Hotel
    roomname= models.CharField(max_length=50,choices = ROOM_CHOICES)
    roomtype = models.CharField(max_length=50,choices = ROOM_TYPE)
    capacity = models.IntegerField()
    price = models.IntegerField()
    # price2 = models.IntegerField(null=True)
    price2 = models.CharField(max_length=10, blank=True, default="None")
    size = models.IntegerField()
    img = models.ImageField(upload_to=f'rooms/',null=True, blank=True)
    img2 = models.ImageField(upload_to=f'rooms/',null=True, blank=True)
    img3 = models.ImageField(upload_to=f'rooms/',null=True, blank=True)
    img4 = models.ImageField(upload_to=f'rooms/',null=True, blank=True)
    dis=models.CharField(db_column="Room Description", max_length=1000, null=True, default="")
    status = models.CharField(choices =ROOM_STATUS,max_length = 15)
    date_disable = models.CharField(max_length=50, blank=True, default="")
    date_disable1 = models.CharField(max_length=50, blank=True, default="")
    date_disable2 = models.CharField(max_length=50, blank=True, default="")
    max_price_date1 = models.CharField(max_length=50, blank=True, default="")
    max_price_date2 = models.CharField(max_length=50, blank=True, default="")
    # roomnumber = models.IntegerField()
    def __str__(self):
        return self.roomname



class Roomimg(models.Model):
  room = models.ForeignKey(Room, on_delete=models.CASCADE)
  updateimg = models.ImageField(upload_to=f'rooms/',null=True)
  

class Reservation(models.Model):
  # room = models.ForeignKey(Room, on_delete = models.CASCADE)
  user = models.ForeignKey(User, on_delete=models.CASCADE)
  name = models.CharField(max_length = 120, default="")
  phone = models.CharField(max_length = 10, default="")
  email = models.EmailField(max_length = 50, default="")
  bookIn = models.CharField(max_length = 50,blank=True, default="")
  bookOut = models.CharField(max_length = 50,blank=True, default="")
  roomname = models.CharField(db_column="Room Name", choices=ROOM_CHOICES, max_length=100,default="")
  roomamt = models.CharField(max_length = 50,blank=True, default="")
  noofroom = models.CharField(max_length=15,blank=True, default="")
  adult = models.CharField(max_length=15,blank=True, default="")
  exper = models.CharField(max_length=15,blank=True, default="")
  kids = models.CharField(max_length=15,blank=True, default="")
  # pay = models.CharField(db_column="Payment", choices=PAYMENT, max_length=15,blank=True, default="")
  amount = models.CharField(max_length=10, blank=True, default="")
  # amount2 = models.CharField(max_length=10, blank=True, default="")
  t = models.CharField(max_length=10,blank=True, default="")
  tamount = models.CharField(max_length=10,blank=True, default="")
  date = models.CharField(max_length = 50,blank=True, default="")
  razorpayid = models.CharField(max_length=255,default="")
  razorpay_payment_id = models.CharField(max_length=255,default="None")
  payment_status = models.BooleanField(default=False)
  cancel = models.BooleanField(default=False)
  checkin = models.BooleanField(default=False)
  checkin_time = models.CharField(max_length = 50,blank=True,default="")
  checkout = models.BooleanField(default=False)
  checkout_time = models.CharField(max_length = 50,blank=True,default="")
  pre_bookIn = models.CharField(max_length = 50,blank=True, default="")
 
  # kidage = models.CharField(max_length=15, blank=True, default="")
  

  def __str__(self):
    return 'Guest Name: %s Guest Phone: %s Type of Room: %s Book in: %s Book out: %s'%(self.name, self.phone, self.roomname, self.bookIn, self.bookOut)

  # def is_past_due(self):
  #   return date.today() > self.bookIn

  # def price(self):
  #     delta = self.bookOut - self.bookIn
  #     if delta.days == 0:
  #         payment = int(self.Room.roomname.price) * int((1 + delta.days)) * int(self.noofroom)
  #     else:
  #         payment = int(self.Room.roomname.price) * int((delta.days)) * int(self.noofroom)
  #     return payment

# class PaymentDetails(Base):
#   uuid = models.UUIDField(default=uuid.uuid4, editable=False)
#   user = models.CharField(max_length=20 , default="")
#   name = models.CharField(max_length=50)
#   amount = models.CharField(max_length=50)
#   email = models.EmailField(max_length=80)
#   mobile = models.CharField(max_length=10 , default="")
#   roomname = models.CharField(max_length=50 , default="")

#   def __str__(self):
#     return self.name+ ' ' +self.roomname

PAYMENT_STATUS = (('Success','Success'),('Pending','Pending'),('Failed','Failed'))
# class RazorpayResponsew(Base):
  
#   response = models.TextField()
#   status = models.CharField(max_length=8,choices=PAYMENT_STATUS)
#   razorpayid = models.CharField(max_length=255,default="")
#   user = models.CharField(max_length=20 , default="")
#   mobile = models.CharField(max_length=10 , default="")
#   roomname = models.CharField(max_length=50 , default="")
#   tamount= models.CharField(max_length=10 , default="")
  

#   def __str__(self):
#     return self.user+ ' ' +self.roomname + ' '+self.tamount + ' '+self.status 


class confom(models.Model):
  user = models.CharField(max_length = 120, default="")
  resvno = models.CharField(max_length = 120, default="")
  name = models.CharField(max_length = 120, default="")
  phone = models.CharField(max_length = 10, default="")
  email = models.EmailField(max_length = 50, default="")
  date = models.CharField(max_length = 50,blank=True, default="")
  bookIn = models.CharField(max_length = 50,blank=True, default="")
  bookOut = models.CharField(max_length = 50,blank=True, default="")
  roomname = models.CharField(db_column="Room Name", choices=ROOM_CHOICES, max_length=100,default="")
  roomamt = models.CharField(max_length = 50,blank=True, default="")
  noofroom = models.CharField(max_length=15,blank=True, default="")
  adult = models.CharField(max_length=15,blank=True, default="")
  exper = models.CharField(max_length=15,blank=True, default="")
  kids = models.CharField(max_length=15,blank=True, default="")
  # pay = models.CharField(db_column="Payment", choices=PAYMENT, max_length=15,blank=True, default="")
  amount = models.CharField(max_length=10,blank=True, default="")
  t = models.CharField(max_length=10,blank=True, default="")
  tamount = models.CharField(max_length=10,blank=True, default="")
  razorpayid = models.CharField(max_length=255,default="")
  razorpay_payment_id = models.CharField(max_length=255,default="None")
  payment_status = models.BooleanField(default=True)
  cancel = models.BooleanField(default=False)

  def __str__(self):
    return self.name+ ' ' +self.roomname + ' '+self.tamount + ' '+' True'


class Feedback(models.Model):
  # user = models.ForeignKey(User, on_delete=models.CASCADE)
  name = models.CharField(max_length = 120, default="")
  email = models.EmailField(max_length = 50, default="")
  phone = models.CharField(max_length = 10, default="")
  feedback = models.CharField(max_length = 500000,blank=True,default="")

  def __str__(self):
    return 'Guest Name: %s Guest Email: %s'%(self.name, self.email)

HotelShevaroys/webapp/forms.py
from django import forms

from webapp.models import *

class ReservationForm(forms.ModelForm):
    class Meta:
        model = Reservation
        fields = '__all__'

HotelShevaroys/webapp/templates/booking/bookroom.html
{% extends "base.html"%}
{% load static %}
{% block content %}
</div>

<div class="elements ptb-80 text-center  ">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="section-title mb-50">
                    <h2><span>Room Booking</span></h2>
                </div>
            </div>
        </div>
    </div>
    <div class="contact-form-info text-center ptb-500 white_bg">
        <div class="container">
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="contact-form">
                        <div class="contact-form-title mb-10">

                        </div>
                        <div class="contact-form-inner">
                            <form method="post" >{% csrf_token %}
                                <div class="form-field-top mb-20">
                                    <div class="form-field-name">
                                        <input name="name" type="text" value="{{request.user.profile.name}}" placeholder="Name" required="">
                                    </div>
                                    <div class="form-field-name">
                                        <input name="phone" type="text" maxlength="10" value="{{request.user.profile.mobile}}"placeholder="Mobile" required="">
                                    </div>
                                </div>
                                <div class="form-field-top mb-20">
                                    <div class="form-field-name">
                                        <input name="email" type="text" value="{{request.user.profile.email}}" placeholder="Email" required="">
                                    </div>
                                    <div class="form-field-name">
                                              
                                        <input name="roomname" required id="id_roomname" value="{{r.roomname}}" selected readonly>
                    
                                    </div>
                                </div>
                                <div class="form-field-name mb-20">
                                    <input name="roomamt" type="text" placeholder="Room Rent per day" value="{{r.price}}" readonly>
                                    <p style="color:blueviolet;">*Price Changes in Special days.</p>
                                </div>
                                <div class="form-field-top mb-20">
                                    <!-- <div class="form-field-name">
                                            
                                        <input name="noofroom" type="text" maxlength="2" placeholder="No Of Rooms" value="{{r.noofroom}}" readonly>
                                            
                                    </div> -->

                                    <!-- <div class="form-field-name">
                                        <input name="adult" type="text" maxlength="2" placeholder="Adult">
                                        <p style="color:red;">*Per room 2 Adult only.</p>
                                    </div> -->

                                    <div class="form-field-name mb-20">
                                        <select name="noofroom" id="id_noofroom"  required>
                                            <option value="" selected>No Of Rooms</option>
                                            <option value="1">1</option>
                                            <option value="2">2</option>
                                            <option value="3">3</option>
                                            <option value="4">4</option>
                                            <option value="5">5</option>
                                            
                                        </select>
                                    </div>
                                
                                    <div class="form-field-name">
                                        <select name="adult" id="id_adult"  required>
                                            <option value="" selected>Adult</option>
                                            <option value="1">1</option>
                                            <option value="2">2</option>
                                        </select>
                                        <p style="color:blueviolet;">*Each Room maximum 2 Adult only. If above add to Extra Person.</p>
                                    </div>
                                </div>
                                <div class="form-field-top mb-20">        
                                                                    
                                    <!-- <div class="form-field-name">
                                        <input name="kids" type="text" maxlength="2" placeholder="Kids" required="">
                                        <p style="color:red;">*Kids age Should be below 10. If above 10, add to Extra Person.</p>
                                    </div>
                                    <div class="form-field-name">
                                        <input name="exper" type="text" maxlength="2" placeholder="Extra Persons" required="">
                                    </div> -->
                                    <div class="form-field-name">
                                        <select name="kids" id="id_kids"  required>
                                            <option value="" selected>Kids</option>
                                            <option value="0">0</option>
                                            <option value="1">1</option>
                                            <option value="2">2</option>
                                            <option value="3">3</option>
                                            <option value="4">4</option>
                                            <option value="5">5</option>
                                            <option value="6">6</option>
                                        </select>
                                        <p style="color:blueviolet;">*Each Room maximum 2 kids only. Kids age Should be below 10. If above 10, add to Extra Person.</p>
                                    </div>
                                    <div class="form-field-name">
                                        <select name="exper" id="id_exper"  required>
                                            <option value="" selected>Extra Persons</option>
                                            <option value="0">0</option>
                                            <option value="1">1</option>
                                            <option value="2">2</option>
                                            <option value="3">3</option>
                                            <option value="4">4</option>
                                            <option value="5">5</option>
                                        </select>
                                        <p style="color:blueviolet;">*Each Room maximum 1 Extra Person only. For each Extra Person ₹.800 will be Charged.</p>
                                    </div>
                                    
                                </div>
                                <div class="form-field-top mb-20">
                                    <div class="form-field-name">
                                        <input name="bookIn" type="text" class="date-picker"  placeholder="Check In" required>
                                    </div>
                                    <div class="form-field-name">
                                        <input name="bookOut" type="text" class="date-picker" placeholder="Checkout" required>
                                    </div>
                                </div>

                                                        
                                <div class="form-field-bottom">
                                    <div class="submit mt-30">
                                        <button type="submit">Make a Book</button>
                                    </div>
                                </div>

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
 
{% endblock %}

HotelShevaroys/webapp/templates/booking/cancel_booking_list.html
{% extends "base.html"%}
{% load static %}
{% block content %}
</div>
<script type="text/javascript">
   //exporte les données sélectionnées
    var $table = $('#table');
    $(function () {
        $('#toolbar').find('select').change(function () {
            $table.bootstrapTable('refreshOptions', {
                exportDataType: $(this).val()
            });
        });
    })

    var trBoldBlue = $("table");

    $(trBoldBlue).on("click", "tr", function (){
        $(this).toggleClass("bold-blue");
    });
</script>
<div class="elements ptb-80 text-center  ">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="section-title mb-50">
                    <h2>My  <span>Cancelled Booking</span> List</h2>
                </div>
            </div>
        </div>
    </div>
          
    <div class="hotel-team white_bg">
        <div class="container">
            <div class="col-md-12">
                <table class="table">
                    <thead>
                        <tr>
                            <td><b style="text-align: center;">Booking Id</b></td>
                            <td><b style="text-align: center;">User</b></td>
                            <td><b style="text-align: center;">Room</b></td>
                            <td><b style="text-align: center;">Total Rooms</b></td>
                            <td><b style="text-align: center;">Adult</b></td>
                            <td><b style="text-align: center;">Kids</b></td>
                            <td><b style="text-align: center;">Check in</b></td>
                            <td><b style="text-align: center;">Check out</b></td>
                            <td><b style="text-align: center;">Payment ID</b></td>
                            <td><b style="text-align: center;">Payment Status</b></td>
                            <td><b style="text-align: center;">Booking Status</b></td>
                        </tr>
                    </thead>
                    <tbody>
                        {% for i in bookings %}
                            <tr>
                                <td>{{i.id}}</td>
                                <td>{{i.name}}</td>
                                <td>{{i.roomname}}</td>
                                <td>{{i.noofroom}}</td>
                                <td>{{i.adult}}</td>
                                <td>{{i.kids}}</td>
                                <td>{{i.bookIn}}</td>
                                <td>{{i.bookOut}}</td>
                                <td>{{i.razorpay_payment_id}}</td>
                                <td style="color: green">Success</td>
                                <td style="color: red;">Booking Cancelled</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
        
       
{% endblock %}

HotelShevaroys/webapp/templates/booking/cancel_booking_view.html
{% extends "base.html"%}
{% load static %}
{% block content %}
</div>
<script type="text/javascript">
   //exporte les données sélectionnées
    var $table = $('#table');
    $(function () {
        $('#toolbar').find('select').change(function () {
            $table.bootstrapTable('refreshOptions', {
                exportDataType: $(this).val()
            });
        });
    })

    var trBoldBlue = $("table");

    $(trBoldBlue).on("click", "tr", function (){
        $(this).toggleClass("bold-blue");
    });
</script>
<div class="elements ptb-80 text-center  ">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="section-title mb-50">
                    <h2><span>Cancel </span> Booking</h2>
                </div>
            </div>
        </div>
    </div>
          
    <div class="hotel-team white_bg">
        <div class="container">
            <div class="col-md-12">
                <table class="table">
                    <h3>Are You Sure, You want to Cancel this Booking?</h3>
                    <br><br>
                    <thead>
                        <tr>
                            <td><b style="text-align: center;">Booking Id</b></td>
                            <td><b style="text-align: center;">User</b></td>
                            <td><b style="text-align: center;">Room</b></td>
                            <td><b style="text-align: center;">Total Rooms</b></td>
                            <td><b style="text-align: center;">Adult</b></td>
                            <td><b style="text-align: center;">Kids</b></td>
                            <td><b style="text-align: center;">Check in</b></td>
                            <td><b style="text-align: center;">Check out</b></td>
                        </tr>
                    </thead>
                    <tbody>
                        {% for i in obj %}
                            <tr>
                                <td>{{i.id}}</td>
                                <td>{{i.name}}</td>
                                <td>{{i.roomname}}</td>
                                <td>{{i.noofroom}}</td>
                                <td>{{i.adult}}</td>
                                <td>{{i.kids}}</td>
                                <td>{{i.bookIn}}</td>
                                <td>{{i.bookOut}}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <a href="{% url 'cancel_booking' id %}" class="btn waves-effect waves-light btn-danger">Cancel Booking</a>&emsp;
                <a href="{% url 'mybooking' %}" class="btn waves-effect waves-light btn-primary"> No </a>
            </div>
        </div>
    </div>
</div>

{% endblock %}

HotelShevaroys/webapp/templates/booking/payment.html
{% extends "base.html"%}
{% load static %}
{% block content %}
</div>
<div class="elements ptb-80 text-center  ">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="section-title mb-50">
                    <h2>Conform <span>Your Details</span></h2>
                </div>
            </div>
        </div>
    </div>
    <div class="contact-form-info text-center ptb-500 white_bg">
        <div class="container">
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="contact-form">
                        <div class="contact-form-title mb-10">

                        </div>
 
                         <div class="contact-form-inner">

                            
                            <form method="POST" action=""> {% csrf_token %}
                                <script
                                    src="https://checkout.razorpay.com/v1/checkout.js"
                                    data-key="rzp_live_J8nQ5tgrIyEcQI" // Enter the Key ID generated from the Dashboard
                                    data-currency="INR"
                                    data-amount={{am}}
                                    data-order_id="{{no}}"
                                    data-buttontext="Conform Pay"
                                    data-name="Hotel Shevaroys"
                                    data-description="{{rn}} Booking"
                                    data-netbanking="true"
                                    data-image="{% static 'images/logo/rp.png' %}"
                                    data-prefill.name={{n}}
                                    data-prefill.email={{e}}
                                    data-prefill.contact={{p}}
                                    data-theme.color="#F37254" 
                                >
                                            
                                </script>
                                <input type="hidden" custom="Hidden Element" name="hidden">
                            </form>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}